---
title: "Descriptive Statistics on Guns and Butter"
author: Daniel Kent
date: "`r Sys.Date()`"
output:     
    tint::tintHtml:
        toc: true
---

# Overview

- What does the distribution of real world gdp, government expenditures, and military spending look like? Who are the countries with the largest military burdens? Relating to the computational model, the distribution of gdp, government expenditures, and gdp/government expenditures will give us useful starting points economically for the model.

- I'm just using 2017 data here, since it likely is the highest quality and contains the least missingness. Also, since the goal is just to get a sense of distributional qualities, the most recent year should be representative of general trends.

# Import the data

```{R message = FALSE}
## libraries
library(dplyr)
library(ggplot2)
library(rio)
library(tikzDevice)

## data
econ_dat <- import("real_dat.rds")

## useful manipulations
econ_dat$mil_gdp <- (econ_dat$milex/econ_dat$gdp) * 100 # percent
econ_dat$mil_govexp <- (econ_dat$milex/econ_dat$gov_exp) * 100
econ_dat$govexp_gdp <- (econ_dat$gov_exp/econ_dat$gdp) * 100
```

# Visuals

## Economic capacity

- These should influence the starting parameters for the model

### GDP 

- Raw

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/GDP
ggplot(data = econ_dat, aes(x = gdp)) + 
    geom_histogram() + 
    theme_bw()
```

- Logged

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/GDP
ggplot(data = econ_dat, aes(x = log(gdp))) + 
    geom_histogram() + 
    theme_bw()
```

### Gov expenditures

- Raw

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/GDP
ggplot(data = econ_dat, aes(x = gov_exp)) + 
    geom_histogram() + 
    theme_bw()
```

- Logged

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/GDP
ggplot(data = econ_dat, aes(x = log(gov_exp))) + 
    geom_histogram() + 
    theme_bw()
```

### Gov expenditures as a percent of GDP

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/GDP
ggplot(data = econ_dat, aes(x = govexp_gdp)) + 
    geom_histogram() + 
    geom_density() + 
    theme_bw()

arrange(econ_dat[,c(1:3, 9)], -govexp_gdp)[1:25,]
```

## Military spending

- These should generally be generated in the model's static state

### Military spending

- Raw

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/GDP
ggplot(data = econ_dat, aes(x = milex)) + 
    geom_histogram() + 
    theme_bw()
```

- Logged

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/GDP
ggplot(data = econ_dat, aes(x = log(milex))) + 
    geom_histogram() + 
    theme_bw()
```

### Military spending as a percent of gdp

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/GDP
mil_gdp <- ggplot(data = econ_dat, aes(x = mil_gdp)) + 
    geom_histogram() + 
    theme_bw() + 
    labs(
        x = "Percent of GDP",
        y = "Count",
        title = "Military Spending/GDP"
    ) + 
    theme(
        text = element_text(size = 12),
        axis.text = element_text(color = 'black')
    )

#ggsave(
#    filename = "mil_gdp.pdf",
#    mil_gdp
#)
```

### Military spending as a percent of expenditures

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Military Spending/Govexp
mil_govexp <- ggplot(data = econ_dat, aes(x = mil_govexp)) + 
    geom_histogram() + 
    theme_bw() + 
    labs(
        x = "Percent of Government Expenditures",
        y = "Count",
        title = "Military Spending/Gov Spending"
    ) + 
    theme(
        text = element_text(size = 12),
        axis.text = element_text(color = 'black')
    )

#ggsave(
#    filename = "mil_govexp.pdf",
#    mil_govexp
#)
```

### Side-by-Side

```{R}
require(cowplot)
mil_gdp_govexp <- plot_grid(mil_gdp, mil_govexp, ncol = 2)

#ggsave(
#    filename = "mil_gdp_govexp.pdf",
#    mil_gdp_govexp,
#    width = 8,
#    height = 4
#)
```

- Who spends the most?

```{R}
## Who spends the most?
arrange(econ_dat[,c(1:3, 8)], -mil_govexp)[1:25,]
```


# ISA Figures

```{R}
library(ggplot2)
library(hrbrthemes)
library(magick)
library(showtext)


## DK: Custom font?
## Slabo 27px is a personal favorite
## Need to download slabo 27 from google fonts and install
font_add_google(name = "Slabo 27px")
font_add("Slabo", "Slabo27px-Regular.ttf")
showtext_auto() ## automatically use showtext for new devices
myfont1 <- "Slabo"

# Basic graph
p1 <- ggplot(
        data = econ_dat,
        aes(x = mil_gdp)
    ) + 
    geom_histogram() + 
    labs(
        title = 'Military Spending as a Percent of GDP',
        subtitle = '2016',
        x = 'Percent',
        y = 'Count',
        caption = 'Source: World Bank, SIPRI'
    )



# Adjust colors -- these are up to you
p1 <- p1 + 
    theme_ipsum() + # great minimalist theme
    theme(
        text = element_text(family = myfont1),
        plot.title = element_text(color = '#000000', size = 20),
        plot.subtitle = element_text(color = '#000000', size = 16),
        plot.caption = element_text(color = '#000000', 
            face = 'bold', size = 12),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(color = "black", size = 14),
        axis.text.y = element_text(color = "black", size = 14)
    )

p1

p2 <- ggplot(
        data = econ_dat,
        aes(x = mil_govexp)
    ) + 
    geom_histogram() + 
    labs(
        title = 'Military Spending as a Percent of Government Expenditures', subtitle = '2016',
        x = 'Percent',
        y = 'Count',
        caption = 'Source: World Bank, SIPRI'
    )

# Adjust colors -- these are up to you
p2 <- p2 + 
    theme_ipsum() + # great minimalist theme
    theme(
        text = element_text(family = myfont1),
        plot.title = element_text(color = '#000000', size = 20),
        plot.subtitle = element_text(color = '#000000', size = 16),
        plot.caption = element_text(color = '#000000', 
            face = 'bold', size = 12),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(color = "black", size = 14),
        axis.text.y = element_text(color = "black", size = 14)
    )

p2

pgrid <- cowplot::plot_grid(p1, p2, ncol = 2)
ggsave(
    filename = "mil_cost.pdf", 
    pgrid, 
    width = 18, 
    height = 11,
    unit = "in")
```

# Distributional tests

- What statistical distributions best fit the observed data?

- fitdistplus
    - https://cran.r-project.org/web/packages/fitdistrplus/vignettes/paper2JSS.pdf
    - https://cran.r-project.org/web/packages/fitdistrplus/fitdistrplus.pdf
    - https://cran.r-project.org/web/packages/fitdistrplus/vignettes/Optimalgo.html
    - https://cran.r-project.org/web/packages/fitdistrplus/vignettes/FAQ.html

- Clauset Shalizi 

- Should we actually assign the observed data to the agents in the model?